__version__ = "0.0.4"
__author__ = "Job Snijders"
__author_email__ = "job@ntt.net"
__copyright__ = "Copyright 2020, Job Snijders"
__license__ = "ISC"
__status__ = "Stable"
__url__ = "https://github.com/job/rpki-ov-checker"
